GET http://localhost:3000/posts

GET http://localhost:3000/posts/5e1fdf79b616071964651d23


POST http://localhost:3000/posts HTTP/1.1
content-type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTI0ODVmNTFmMmM0NzA2MzBmNzBhNjciLCJpYXQiOjE1Nzk0NTc3MTF9.2WngjOQltfvxrQlaIoIUwOSY2OV0b-tWtHISwD_dTj0

{
    "title": "sample",
    "description": "Wed, 21 Oct 2015 18:27:50 GMT"
}

PATCH http://localhost:3000/posts/5e1fdf79b616071964651d23 HTTP/1.1
content-type: application/json

{
    "title": "This title sucks dick for a living"
}

POST http://localhost:3000/user/register HTTP/1.1
content-type: application/json

{
    "name": "ezequiel",
    "email": "ezequiel@gmail.com",
    "password": "12345678"
}

POST http://localhost:3000/user/login HTTP/1.1
content-type: application/json

{
    "email": "ezequiel@gmail.com",
    "password": "12345678"
}

